### ISSUE TITLE
Nav Walker breaks Shiftnav (off-canvas menu plugin)

### ISSUE THREAD

**Issue by ptibbetts** [roots/soil#105]
I'm nearing the end of a project and noticed that [Shiftnav](http://shiftnav.io/) (off-canvas menu plugin) wasn't fully applying its JavaScript to the menu items and so I've had to disable Soil for the time being.

I suspect that Shiftnav is to blame here and that using any custom walker would cause it to stop working however I wanted to note this down somewhere (I've also opened a ticket on [the plugin's support forum](https://wordpress.org/support/topic/conflict-with-soil-plugin) for those who want to follow along).

Is it possible to use Soil without the walker? Could Soil benefit from an options page to enable/disable the individual modifications it makes?

**Comment by swalkinshaw** [comment]
Of course. It's only enabled with `add_theme_support('soil-nav-walker');`, so just don't add that.

It's on the `README` :)

**Comment by ptibbetts** [comment]
![facepalm](https://media1.giphy.com/media/kwQfk9zUJ6eVq/200.gif)

… I'd forgotten Sage already does this for me

thanks Scott
