### ISSUE TITLE
Soil breaks FooGallery thumbnails

### ISSUE THREAD

**Issue by jmotes** [roots/soil#106]
With the soil plugin enabled ~~(on any theme)~~ and theme support for relative urls added, [FooGallery](https://wordpress.org/plugins/foogallery/) custom sized thumbnails no longer work and get replaced by the full size image.

FooGallery uses the WP Image Editor class to make the thumbnails. Could soil be modified to retain image edits instead of using the main image?

**Comment by QWp6t** [comment]
Does this fix it?

```php
remove_filter('wp_get_attachment_url', 'Roots\\Soil\\Utils\\root_relative_url');
```

**Comment by jmotes** [comment]
@QWp6t Re-tested today. I thought it became an issue as soon as soil was activated, but it's onlywhen theme support for "soil-relative-urls" is added. With theme support added, the remove_filter code does not seem to help.

**Comment by QWp6t** [comment]
You would need to remove the filter after it gets added. It gets added at `after_setup_theme` hook.

```php
add_action(`after_setup_theme`, function () {
  remove_filter('wp_get_attachment_url', 'Roots\\Soil\\Utils\\root_relative_url');
});
```

Or just disable the module.

**Comment by jmotes** [comment]
Yes that works, thanks! I'll just do that for now so that the rest of my urls at least can be root relative.

By the way, I went through the FooGallery code and didn't find a place for Soil to hook into it's source code directly. It appears to be modifying the results from the [WPThumb library](https://wordpress.org/plugins/wp-thumb/) that it uses.

**Comment by QWp6t** [comment]
We're going to make this easier to do with #104. But for now the way you're doing it should work.
