### ISSUE TITLE
jQuery in the footer when jQuery called in body

### ISSUE THREAD

**Issue by asuh** [roots/soil#107]
When I add `add_theme_support('soil-jquery-cdn');`, jQuery is moved to the footer by default. All good except when jQuery is inserted into the content somewhere.

Inspect the section where Google Maps is embedded:
http://themes.kadencethemes.com/pinnacle/contact-us/

When jQuery is added to the footer, this embedded Google Map won't display. Maybe there should be an option to keep jQuery in `<head>` for edge cases like this?

**Comment by retlehs** [comment]
you shouldn't be inserting javascript in the middle of your document like that

also, jquery will show up in the header if you (or a plugin) tell wordpress to enqueue a script that depends on jquery

**Comment by asuh** [comment]
I'm using the referenced theme above for a client so I'm at the theme author's mercy on this one. I hear ya, inserting JS in content isn't optimal but I'm also not interested to hack it considering the pay haha

I figure this edge case would be common on themes outside of Sage considering many theme authors don't follow best practices but I understand if you're not interested to provide option since this is kind of an edge case.
