### ISSUE TITLE
No dropdown class

### ISSUE THREAD

**Issue by Bobz-zg** [roots/soil#109]
There is no class indicating that menu item has submenu.

**Comment by retlehs** [comment]
fact. 

what's the issue? there are no plans on adding a `dropdown` class. you can write your styles in a way that doesn't require it

**Comment by Bobz-zg** [comment]
Hmm..
How could I add arrow indicating that there is a submenu?

**Comment by retlehs** [comment]
with CSS :100: 

using the power of google, i came across this: http://stackoverflow.com/questions/5281556/is-there-a-css-way-to-add-an-arrow-if-a-ul-has-a-ul-child

closing since github isn't the place for support. (support also wouldn't cover writing CSS)

**Comment by Bobz-zg** [comment]
Spot on, thanks.
Nav walker from roots theme had 'dropdown' class.
