### ISSUE TITLE
Relative urls and frontend ajax

### ISSUE THREAD

**Issue by ajoah** [roots/soil#111]
This soil code permit to check if we must disable relative url feature or not:
```php
function enable_root_relative_urls() {
  return !(is_admin() || preg_match('/sitemap(_index)?\.xml/', $_SERVER['REQUEST_URI']) || in_array($GLOBALS['pagenow'], ['wp-login.php', 'wp-register.php']));
}
```
https://github.com/roots/soil/blob/master/modules/relative-urls.php#L17

Ok, it disable the feature in admin but there is a problem : it disables relative urls for frontend ajax requests too :/

For the moment i have patched the function like this :
```php
function enable_root_relative_urls() {
  return (isset($_REQUEST['my_frontend_call']) && defined('DOING_AJAX') && DOING_AJAX) || !(is_admin() || preg_match('/sitemap(_index)?\.xml/', $_SERVER['REQUEST_URI']) || in_array($GLOBALS['pagenow'], ['wp-login.php', 'wp-register.php']));
}
```
Nevertheless this forces to add a variable to each ajax call.

**Comment by retlehs** [comment]
you can now use a filter: #104

**Comment by ajoah** [comment]
Nice, thank you
