### ISSUE TITLE
Relative urls not working anymore

### ISSUE THREAD

**Issue by schoenkaft** [roots/soil#118]
The relative-urls refactoring in 1.5.0 broke all relative urls for one our clients websites.
The problem is that our `WP_SITEURL` is different from the url we're requesting from. This is done because we're accessing the admin from a single server (non-https), while the front part of the system is accessed thru a load balancer and hosted on multiple servers (https, with CloudFront on top of it).

```
WP_HOME=https://<domain>.net
WP_SITEURL=http://admin.<domain>.net/wp
```

This means that `$hosts_match = $site_url['host'] === $url['host'];` will never match, and therefore return false and will not be made relative.

Absolute url's wouldn't be a big problem, if it wouldn't be for the fact that our `WP_SITEURL` is non-https (since we don't have a certificate for it), while the visitor facing part of the website is completely https. This means that the assets asset urls are `http://<domain>.net/<asset>`, and they get blocked by the browser since they're not https. So we're actually relying on relative url's, since they don't care about protocol. 

My solution for now is to revert to 1.4.0 or disable the $hosts_match.
Another solution for me would be to strip the protocol from the `return $input;`, like `return preg_replace('#^https?:#', '', $input);`, so the absolute url becomes `//<domain>.net/<asset>`.

I guess this is sort of an edge case, but with the current version (1.5.0) stuff is not working for me anymore.

**Comment by QWp6t** [comment]
Can you confirm for me real quick that this fixes it?

https://github.com/roots/soil/blob/master/lib/utils.php#L13

```diff
   if (!isset($url['host']) || !isset($url['path'])) {
     return $input;
   }
-  $site_url = parse_url(network_site_url());  // falls back to site_url
+  $site_url = parse_url(network_home_url());  // falls back to site_url
   if (!isset($url['scheme'])) {
     $url['scheme'] = $site_url['scheme'];
   }
```

Just make that change in your local copy and let me know if everything's working.

**Comment by schoenkaft** [comment]
It fixes the first part, but still the `$schemes_match` returns false, since the `WP_HOME` uses a different scheme than the `WP_SITEURL`.

**Comment by retlehs** [comment]
sorry, but not going to support this sort of use case

https all of the things :wink:
