### ISSUE TITLE
Permalink URLs are not always made relative (inconsistency)

### ISSUE THREAD

**Issue by ollietreend** [roots/soil#119]
Hi,

I've noticed that the output of `the_permalink()` is filtered, but the same is not done for `get_permalink()`.

[Link to relevant code.](https://github.com/roots/soil/blob/4e9ad4562e1592c49f1f3a26c4dad1e00500c0c0/modules/relative-urls.php#L21-L38)

I know that it's possible to hook in to the `soil/relative-url-filters` filter and add `get_permalink` to the array. However, I'm wondering whether there's a reason why this hasn't already been done – perhaps there would be negative repercussions to this? Perhaps `get_permalink()` is being used somewhere that absolute URLs are required (e.g. published RSS feed, pingbacks, etc.) and therefore this value is not being filtered?

It there a reason for the exclusion of `get_permalink()` but the inclusion of `the_permalink()`? Or is this a bug?

I want to get a relative URL for a post, but now I'm wondering the best way to go about it. I could capture the output of `the_permalink()` in an output buffer and then use that. It's a clunky way around it, but I'm puzzled by the lack of `get_permalink()` filtering, and hesitant to enable it in case it breaks something that I'm not aware of.

Thanks

**Comment by ollietreend** [comment]
On second thoughts – rather than use an output buffer, I can just apply `the_permalink` filter manually myself:

```php
$url = apply_filters('the_permalink', get_permalink($post_object));
```

But my questions remain – I'm interested in whether this is a bug, or a deliberate inconsistency.

**Comment by retlehs** [comment]
> Perhaps get_permalink() is being used somewhere that absolute URLs are required (e.g. published RSS feed, pingbacks, etc.) and therefore this value is not being filtered?

^^^
