### ISSUE TITLE
Soil 3.5.0 not compatible with Sage 8.3.0

### ISSUE THREAD

**Issue by pvds** [roots/soil#121]
After receiving the wonderfull news that Sage 8.3.0 was released I updated my Sage fork and came to the conclusion Soil 3.5.0 is not working.

The culprit is line 65 in soil.php:
```php
add_action('after_setup_theme', __NAMESPACE__ . '\\load_modules');
```

In the Master branch of Soil this code is updated with a priority:
```php
add_action('after_setup_theme', __NAMESPACE__ . '\\load_modules', 100);
```

As a temporary fix, require the master version of Soil with composer in your projects dependencies and run composer update:
```
composer require roots/soil dev-master
composer update
```

Please release a new version of Soil

**Comment by unholyknight** [comment]
Adding priority to add_action in soil.php fixed the issue with Soil 3.5.0 for me. This was about to drive me insane, thanks for this.

**Comment by retlehs** [comment]
@unholyknight correct. it's already in master https://github.com/roots/soil/pull/120

will tag a new release soon.

**Comment by frozzare** [comment]
@retlehs when will the new release be out?
