### ISSUE TITLE
WordPress 4.4 img srcset URIs not relative

### ISSUE THREAD

**Issue by Einkoro** [roots/soil#131]
Looks like filtering these will require adding a new function as the only filter with the URIs is an array containing the URI and other data: 
https://core.trac.wordpress.org/browser/tags/4.4/src/wp-includes/media.php#L1096
https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

Quick and dirty example dropped in modules/relative-urls.php:
```
Utils\add_filters('wp_calculate_image_srcset', function($sources) {
  foreach ($sources as $source) {
    $source['url'] = \Roots\Soil\Utils\root_relative_url($source['url']);
  }
  return $sources;
});
```

**Comment by retlehs** [comment]
fixed, thanks!

**Comment by michelkusters** [comment]
I'm working on a multilingual website (built with WPML) that uses multiple domains (one per language).

On the main domain/language, img srcset is now relative.
On all other domains/languages, img srcset is not relative and includes the main domain/language.

To fix this, I hacked away in soil/lib/utils.php and changed:
From: `$hosts_match = $site_url['host'] === $url['host'];`
To: `$hosts_match = strpos($site_url['host'], 'denheuvel') !== false; // check if the hostname contains "denheuvel"`

Note that I`m not a back end dev, but I hope this comment is helpful :)
