### ISSUE TITLE
Should not return relative URLs in feeds

### ISSUE THREAD

**Issue by danielvonmitschke** [roots/soil#135]
if (is_feed()) {
      return $input;
  }

as first line in roots_relative_url() function should do the trick. :)

best,

daniel

**Comment by retlehs** [comment]
or https://github.com/roots/soil/blob/8b534d4b271033d22b8fa0d055c740f7f9c4ca58/modules/relative-urls.php#L17

thanks for the issue!

**Comment by retlehs** [comment]
@danielvonmitschke what specifically are you seeing in the feed that's being returning as root relative? all the filters we're currently running relative URLs on appear to be unaffected by anything that would show up in the feed

**Comment by danielvonmitschke** [comment]
I was prepending the post-thumbnail to the feed content by calling `get_the_post_thumbnail`.
There is also a plugin that is doing this: http://wordpress.org/plugins/featured-images-for-rss-feeds/

**Comment by retlehs** [comment]
thanks for the quick reply!

**Comment by retlehs** [comment]
fixed in #145, sorry for the delay

**Comment by danielvonmitschke** [comment]
thanks :)
