### ISSUE TITLE
load_modules() theme supports

### ISSUE THREAD

**Issue by bryanwillis** [roots/soil#139]
It looks like [`require_if_theme_supports()`](require_if_theme_supports) was written for the sole purpose of doing what `load_modules()` does in the main [soil plugin file](https://github.com/roots/soil/blob/master/soil.php#L55). All the modules seem to work fine when testing it out. I would have opened a pull request, but I'm not really sure about what to do with is the `Options::init( $feature )` part and if we need to be using the global for it to work (wasn't really sure how to test it).

``` php
function load_modules() {
  foreach (glob(__DIR__ . '/modules/*.php') as $file) {
    $feature = 'soil-' . basename($file, '.php');
    require_if_theme_supports($feature, $file);
  }
}
add_action('after_setup_theme', __NAMESPACE__ . '\\load_modules', 100);
```

**Comment by QWp6t** [comment]
Thanks for the issue. :+1:

I never got around to implementing this, but now it's no longer needed in `4.0.0`.
