### ISSUE TITLE
Should emojis be removed from tinymce?

### ISSUE THREAD

**Issue by bryanwillis** [roots/soil#143]
Looks like [tinymce registers the emojis](https://github.com/WordPress/WordPress/blob/d0b708fcb9e0aad41f387a9aa5d469679d291097/wp-includes/class-wp-editor.php#L406). Wondering if we should disable this when removing them with [cleanup](https://github.com/roots/soil/blob/master/modules/clean-up.php#L17).

Any thoughts?

```php
add_filter( 'tiny_mce_plugins', 'emojis_mce_disable' );
function emojis_mce_disable( $plugins ) {
	if ( is_array( $plugins ) ) {
		return array_diff( $plugins, array( 'wpemoji' ) );
	} else {
		return array();
	}
}
```

**Comment by retlehs** [comment]
i don't see anything in the visual editor that is related to emojis so i'm not sure if this would be necessary

**Comment by bryanwillis** [comment]
It's loading this in the admin but isn't necessary if emojis are disabled on the frontend: 

[wordpress/wp-includes/js/tinymce/plugins/wpemoji/plugin.js](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/tinymce/plugins/wpemoji/plugin.js)

**Comment by retlehs** [comment]
closing this out as it's not really a big deal (but would be open to a PR)
