### ISSUE TITLE
current jQuery Version (1.12.3) gives 404 on CDN

### ISSUE THREAD

**Issue by dsturm** [roots/soil#152]
Issue in `/modules/jquery-cdn.php` on `register_jquery()`

Using WP 4.5 jQuery 1.12.3 is registered (wp_scripts()->registered['jquery']->ver) but isn't available on https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js. I would like to have an filter to override the reference CDN Version, like:

`$jquery_version = apply_filters('jquery_cdn_version', wp_scripts()->registered['jquery']->ver);`

**Comment by retlehs** [comment]
This is already fixed. Soil uses the jQuery CDN as of 3.7.0.

**Comment by dsturm** [comment]
Wow, ok, thanks for your quick response. Didn't see that I used an outdated version of soil.
