### ISSUE TITLE
Add SRI to jQuery CDN module

### ISSUE THREAD

**Issue by QWp6t** [roots/soil#153]
See PHP example for generating SRI's `integrity` value on this page: http://tenzer.dk/generating-subresource-integrity-checksums/

The newest version of jQuery 1.x, for example, would look like this...

```
<script src="https://code.jquery.com/jquery-1.12.3.min.js" integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/wp/wp-includes/js/jquery/jquery.js"><\/script>')</script>
```

Note that SRI checks aren't needed for self-hosted scripts, like the self-hosted version of jQuery. If there's a MITM between the client and your server, then the MITM would just change the integrity value. But it is probably a good idea to use it for third-party resources.

**Comment by retlehs** [comment]
#228
