### ISSUE TITLE
Relative URLs and Yoast SEO plugin sitemap issue with categories and custom taxonomies

### ISSUE THREAD

**Issue by kmeronuk** [roots/soil#156]
I'm encountering a similar issue to https://github.com/roots/soil/issues/16

The site is currently WP 4.5.2 and Yoast SEO 3.2.5 and I'm seeing the issue with the default WP categories sitemap, as well as two custom taxonomies that I have Yoast generating sitemaps for. 

The sitemaps are being generated with root relative URLs, causing Google Webmaster Tools to give the error "This is not a valid URL. Please correct it and resubmit."

It's fine with the default page/post sitemaps and those for my custom post types. Just the categories and custom taxonomies that are having issues.

The sitemap is http://www.gslholdings.com/sitemap_index.xml

Any help with resolving this issue would be much appreciated.

**Comment by danielvonmitschke** [comment]
Just add this to your functions.php:

`
function remove_relative_links_in_sitemaps() {
	if ( ! isset( $_SERVER['REQUEST_URI'] ) ) {
		return;
	}

	$request_uri = $_SERVER['REQUEST_URI'];
	$extension   = substr( $request_uri, -4 );

	if ( false !== stripos( $request_uri, 'sitemap' ) && in_array( $extension, array( '.xml', '.xsl' ) ) ) {

        remove_filter( 'bloginfo_url', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'the_permalink', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'wp_list_pages', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'wp_list_categories', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'the_tags', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'get_pagenum_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'get_comment_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'month_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'day_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'year_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'term_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'the_author_posts_link', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
        remove_filter( 'wp_get_attachment_url', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
		
	}
    
}

add_action( 'init', 'remove_relative_links_in_sitemaps' );

`

**Comment by retlehs** [comment]
thanks @danielvonmitschke

**Comment by ladislavsulc** [comment]
Hello,

I am using SEO Framework (also tested with Google Sitemap XML plugin) and even this doesn't help. I need absolute URLs inside sitemap AND inside robots.txt: https://www.aristie.cz/robots.txt

Could anyone help me please?

Thank you.

**Comment by mahnunchik** [comment]
It still doesn't work!
