### ISSUE TITLE
Way to disable adding back rel_canonical to wp_head?

### ISSUE THREAD

**Issue by justinelam** [roots/soil#158]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [ ] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

I'm writing a custom function to add a new canonical URL for the site www.vote.org, I have to remove_action('wp_head','rel_canonical') to remove Wordpress' generated URL. 

But it looks like Soil adds it back in. How can I disable adding back the canonical URL without having to disable the entire Soil plugin?

**What is the expected or desired behavior?**

Being able to show our own custom canonical URL via add_action() to wp_head 

---

---

## Feature Request

(delete this section if not applicable)

**Please provide use cases for changing the current behavior:**

Being able to show our own custom canonical URL via add_action() to wp_head

**Comment by QWp6t** [comment]
You can already do this.

Drop this in your theme or plugin or whatever:
```php
add_action('init', function () {
    remove_action('wp_head', 'Roots\\Soil\\CleanUp\\rel_canonical');
}, 15); // $priority = 15 ensures that it's running after Soil.
```

If you need further support, please take this to https://discourse.roots.io/
