### ISSUE TITLE
Relative URLs and Yoast SEO plugin

### ISSUE THREAD

**Issue by antorome** [roots/soil#16]
Hello

If you have roots relative urls enabled, then Yoast SEO sitemap for "tags" are generated incorrectly with just the relative path and having issues in Google Webmaster Tools. I only had this problems with "tags", not with categories, custom posts, etc.

BR

**Comment by kmeronuk** [comment]
I'm also encountering this issue, with WP 4.5.2 and Yoast SEO 3.2.5, where some of the sitemaps generated by Yoast SEO are being output with root relative URLs, causing Google Webmaster Tools to give the error "This is not a valid URL. Please correct it and resubmit."

I'm seeing the issue with the default WP categories sitemap, as well as two two custom taxonomies that I have Yoast generating sitemaps for.

**Comment by mahnunchik** [comment]
It still doesn't work!
