### ISSUE TITLE
Conflict with WPML plugin using relative urls

### ISSUE THREAD

**Issue by h0r0man** [roots/soil#162]
When I use `add_theme_support('soil-relative-urls');` in my `functions.php` the WPML language switcher doesn't add the url. For example `/es/` of :es: language, specifically in `index.php` or `archives.php` when the content is displayed by the date example: `/2016/`, so the correct url must be: `/es/2016/`.

* Maybe the issue it is not related to Soil :raised_hand:
* Also tested on WP clean install using Twenty Sixteen Theme :point_left:

**Comment by QWp6t** [comment]
This is an issue with how WPML sniffs out URLs for it to modify. It's not really something we can fix on our end as far as I know. It looks like you'd probably want to somehow wrap the relative URLs in [`icl_link_to_element()`](https://wpml.org/documentation/support/creating-multilingual-wordpress-themes/hard-coded-theme-links/).

It might be easier to just disable the module, or maybe the WPML guys can offer a better suggestion.
