### ISSUE TITLE
Using soil-clean-up remove unnecessary rel=prev/next

### ISSUE THREAD

**Issue by h0r0man** [roots/soil#163]
When the `add_theme_support('soil-clean-up')` is in use the `rel=prev/next` links disappears, why this is happens? :confused:

**Comment by QWp6t** [comment]
https://github.com/roots/soil/blob/master/modules/clean-up.php#L27

Feel free to re-add it.

```
add_action('init', function () {
    add_action('wp_head', 'adjacent_posts_rel_link_wp_head', 10);
}, 100); // wrap in high priority `init` to ensure it fires after Soil hook
```
