### ISSUE TITLE
Relative URL's in WordPress SEO Sitemap

### ISSUE THREAD

**Issue by Log1x** [roots/soil#170]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

---

**What is the current behavior?**

Relative URL's are shown in sitemap's generated by plugin's such as WordPress SEO

**What is the expected or desired behavior?**

For it to not make the URL's relative.

---

This is a simple fix by changing [line 9](https://github.com/roots/soil/blob/master/lib/utils.php#L9) of lib/utils.php to `if (is_feed() || get_query_var('sitemap')) {` -- doesn't harm or change anything whether a user uses a sitemap generated by a plugin or not.

**Comment by retlehs** [comment]
what version are you on? this should already be fixed as of https://github.com/roots/soil/commit/70f90fb478a15b5cfe12845521d7b4f64d64111e

**Comment by Log1x** [comment]
Ah, I'm indeed on the latest version and overlooked that line in relative-urls.php. Possibly it was just a bug with WordPress SEO it's self? I applied my fix and then updated a post and it fixed but I will retest and open if there is an issue.

Thanks!
