### ISSUE TITLE
Add Hidden Input Support to Search

### ISSUE THREAD

**Issue by Log1x** [roots/soil#173]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [ ] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Adding `<input type="hidden" name="post_type" value="reviews" />` inside of the searches `form` element makes the form not use Nice Search and instead returns `?s=Lorem+ipsum&post_type=reviews`

This is due to `strpos($_SERVER['REQUEST_URI'], '&')  === false`  on line 20 of `nice-search.php` which appears to of been added due to #97.

**What is the expected or desired behavior?**

Potentially add support for hidden values inside of the `form` such as `post_type`.

Possible link could be `/search/Lorem+ipsum/reviews` or even `/search/Lorem+ipsum&post_type=reviews` would be cleaner than reverting to the default output.

---

**Comment by retlehs** [comment]
this is by design, see https://github.com/roots/soil/pull/115

**Comment by Log1x** [comment]
I figured. Any possibility to add a filter? I'm sure I could edit the core but since I require all of my dependencies with composer I hate to have to do that. I'd think there is some way to approach it to make them stay pretty and keep everyone else happy.

**Comment by retlehs** [comment]
@Log1x if ya got any ideas on this let us know, but not something we're likely going to spend time on right now
