### ISSUE TITLE
Relative URL not working as expected

### ISSUE THREAD

**Issue by tormjens** [roots/soil#174]
Hi,

Just encountered this on a fresh install I just made with a fresh Sage install and the only plugin activated being Soil.

The relative URLs are adding an extra slash before the URL, meaning they are interpreted as protocol relative, not directory.

Sage 9.0.0-alpha.4
Soil 3.7.1

![screen shot 2017-01-05 at 12 09 32](https://cloud.githubusercontent.com/assets/3974889/21678652/26d0634a-d340-11e6-9469-00cdfb9fc573.png)

**Comment by retlehs** [comment]
this seems like a misconfiguration with your bedrock/wordpress install rather than being related to this plugin. check your home/siteurl values and please post on https://discourse.roots.io/ if you need further assistance
