### ISSUE TITLE
Leverage browser caching, pagespeed warning

### ISSUE THREAD

**Issue by v3nt** [roots/soil#175]
## Submit a feature request or bug report

- [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x ] This is a feature request
- [ x] This is a bug report
- [x ] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [ x] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Error on Google page speed tests
https://developers.google.com/speed/pagespeed

**What is the expected or desired behavior?**

I know this doesn't affect speed but clients are increasingly using these testing pages and want 100%. Currently at 99%! 

## Feature Request
Any way we can not show the analytics code if its a certain user agent?

```
<?php if (!isset($_SERVER['HTTP_USER_AGENT']) || stripos($_SERVER['HTTP_USER_AGENT'], 'Speed Insights') === false): ?>
// your analytics code here
<?php endif; ?>
```

---

**Comment by retlehs** [comment]
you could prolly use that snippet to conditionally show the analytics by putting the `add_theme_support` call in there? not gonna work if you have page caching though
