### ISSUE TITLE
Remove capital_p_dangit.

### ISSUE THREAD

**Issue by seothemes** [roots/soil#182]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [X] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

WordPress filters the title, content and comments and corrects the spelling.

**What is the expected or desired behavior?**

This is not necessary and could be removed.

---

## Feature Request

```
remove_filter( 'the_title', 'capital_P_dangit', 11 );
remove_filter( 'the_content', 'capital_P_dangit', 11 );
remove_filter( 'comment_text', 'capital_P_dangit', 31 );
```

**Comment by retlehs** [comment]
thanks, but going to pass
