### ISSUE TITLE
The SEO Framework + og:image/twitter:image URLs

### ISSUE THREAD

**Issue by wassim** [roots/soil#187]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

---

**What is the current behavior?**

Duplicated root domain in og:image and twitter:image tags

```
<meta property="og:image" content="http://domain.com/http://domain.com/app/uploads/..." />
<meta name="twitter:image" content="http://domain.com/http://domain.com/app/uploads/..." />
```

**What is the expected or desired behavior?**

The SEO Framework builds full URLs. Soil shouldn't add home url on top of that. (#184)

**How to fix this**

Revert #184

---

## Bug report

**Please provide steps to reproduce, including full log output:**

1) Upload a custom social image for a post using the SEO Settings metabox provided by TSF.

**Please describe your local environment:**

Soil version: 3.7.2

WordPress version: 4.8

Active theme: Sage

Active plugins: The SEO Framework version: 2.9.2

**Where did the bug happen? Development or remote servers?**

Both

**Comment by coliff** [comment]
hi - the twitter images don't work with and without this patch when using the official Twitter WordPress plugin. Twitter images are displayed with a relative URL still, example: <meta name="twitter:image" content="/wp-content/uploads/2017/06/highway-1767106_1920-1.jpg">. Should I open a separate issue regarding this?

**Comment by retlehs** [comment]
@coliff this has since been updated, see #190
