### ISSUE TITLE
SEO Framework social images url are still broken after PR #188

### ISSUE THREAD

**Issue by pierre-dargham** [roots/soil#189]
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [X] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

---

**What is the current behavior?**

After https://github.com/roots/soil/pull/188 , we still have some SEO Framework social images url broken.

- When site is in a subdirectory, we have some social images url like `http://example.com/site_path/web/site_path/web/media/2017/06/image.jpg` (site directory is present twice)

- When using a custom social image URL that isn't part of the current site, issue https://github.com/roots/soil/issues/187 still occurs. Example : `http://example.com/http://images.example.com/image.jpg`

**What is the expected or desired behavior?**

I think that assuming what the `$image` variable passed to the filters contains, and how the url is built (absolute, relative, internal, external ...) is a little hazardous. It could also break some third party filters.

Don't you think we could instead unhook the relative-url filter on `wp_get_attachment_url` during the generation of SEO Framework meta headers ? It would solve the issue in a more generic way, according to the idea that we just don't want to apply the relative-url filters on schema / open-graph / social meta tags (especially images).

---

**Local environment:**

Soil version: master ( https://github.com/roots/soil/commit/4172c0bc04d4d535bf51f06b3d2d738ff8ff44c3 )

WordPress version: 4.8

Active plugins: The SEO Framework 2.9.3

---

**Example fix:**

An example fix would be to replace https://github.com/roots/soil/blob/4172c0bc04d4d535bf51f06b3d2d738ff8ff44c3/modules/relative-urls.php#L52:L54 with :

```php
add_action('the_seo_framework_do_before_output', function () {
  remove_filter('wp_get_attachment_url', 'Roots\\Soil\\Utils\\root_relative_url');
});

add_action('the_seo_framework_do_after_output', function () {
  add_filter('wp_get_attachment_url', 'Roots\\Soil\\Utils\\root_relative_url');
});
```

Bests regards,
Pierre

**Comment by retlehs** [comment]
still? thought it worked in both scenarios for me when testing. i've tried their filters in their past and wasn't able to get that to work. does that example fix work for you? if so, want to submit a PR?

**Comment by pierre-dargham** [comment]
I just checked again both scenario, and I still have the bug. Maybe the bug report wasn't explicit enough (note that https://github.com/roots/soil/pull/188 works in *most* cases, but not *always*). I'll try to give more details :

**1. When WP isn't installed at the vhost root directory :**

If WP runs at url `http://example.com/site_path/web/` then we have :
- `home_url()` returning `http://example.com/site_path/web/`
- filtered `$image` variable equals to `/site_path/web/<image_path>`
- and then we have `home_url($image)` returning `http://example.com/site_path/web/site_path/web/<image_path>`

**2. If a custom ***external*** URL is used :**

If WP runs at url `http://example.com/` and we use a custom social image at `http://images.example.com/image.jpg` then we have :
- `0 === strpos($image, home_url())` returning **false** because `http://example.com/` is no part of `http://images.example.com/image.jpg`
- `home_url($image)` returning `http://example.com/http://images.example.com/image.jpg`

This is why I suggested to avoid modifying directly the image url : we don't know much about the context and parsing the url to match all cases would add unnecessary complexity.

The example fix works for me, and I think it will fit all cases, because we just unhook the relative-url filter on `wp_get_attachment_url` during the bootstrap part when SEO Framework generates the meta headers.

If you agree I'll will submit a PR with this fix

**Comment by retlehs** [comment]
Thanks for all the details and sorry for the issues. The filter fix you showed is definitely ideal, so if you could submit a PR with that it would be much appreciated 😊
