### ISSUE TITLE
Asset versioning with fingerprint/version # in filename

### ISSUE THREAD

**Issue by partounian** [roots/soil#193]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a feature request
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [X] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

We have the option to disable asset-versioning with a query which is good, but it would be great to still have a way to invalidate cache. Google reccommends this:
![screen shot 2017-07-27 at 12 03 50 pm](https://user-images.githubusercontent.com/2541595/28687639-ee3744c6-72c3-11e7-92fc-3279deeee87a.png)

## Feature Request

**Please provide use cases for changing the current behavior:**

To "get the best of both worlds: client-side caching and quick updates"! 😃 

Here is a node.js module which does this https://www.npmjs.com/package/node-version-assets

Note: I am using the full roots stack, Trellis + Bedrock + Roots 8.5.1 + Soil, please notify me if there is a better place to put this.

**Comment by chesio** [comment]
The node.js module you have mentioned makes sense only for assets that you control (ie. your theme essentially), you don't want to rename asset files shipped with WordPress core or plugins...

If you want to invalidate browser cache whenever version number of particular asset changes, but at the same time you don't want to broadcast it, a simple solution is to replace it with its fingerprint (obtained by [wp_hash()](https://developer.wordpress.org/reference/functions/wp_hash/) to have it salted).

I'm not sure if this is something Soil should do by default, as I don't know what's the original intention behind removal of version query string...

**Comment by partounian** [comment]
That's true, I leave that up to the plugin devs. I also realized that roots/sage does have asset versioning so I am using that for my personal files which is the most important part.

**Comment by QWp6t** [comment]
You can use rewrites to do it if you want.

Apache: https://github.com/h5bp/server-configs-apache/blob/master/src/web_performance/filename-based_cache_busting.conf

Nginx: https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/cache-busting.conf

Might have to refactor those, but it would be super similar. You'd filter `script_loader_src` and `style_loader_src` and change the `ver` querystring to be part of the file name.

So `/app/plugins/example/styles.css?ver=1f2e3d4` becomes `/app/plugins/example/styles.1f2e3d4.css`

Also, there's absolutely no reason to salt these hashes. They don't need to be cryptographically secure. Use crc32 or md5. Anything more is overkill.

**Comment by chesio** [comment]
> Also, there's absolutely no reason to salt these hashes. They don't need to be cryptographically secure. Use crc32 or md5. Anything more is overkill.

If you are paranoid about obscuring version numbers, you should salt the hashes. Version numbering space is fairly small (more so if you consider only WordPress existing versions), so it's easy to decrypt plain hashes using rainbow tables.

Not that I recommend this level of paranoia, but then I don't even bother to remove version numbers...

**Comment by QWp6t** [comment]
1. It's not decryption. Hashes don't encrypt anything, ever. Even in a cryptographic setting, hashes don't encrypt anything. It would defeat the purpose of the hash if they did. So there's nothing to decrypt.

2. These hashes aren't being used for cryptography. They're being used for cache-busting public-facing client-side assets. There is no reason to treat it like it's sensitive data. That's bonkers.

If you're using actual version numbers or timestamps, then that's fine; you'd just have to refactor the rewrites for that instead. But typically file hashes (as in, hashes of the file's contents) are preferred because files can be regenerated with the exact same contents, which would cause the timestamp to increment but there's no reason to cache bust if the contents haven't changed. This is why cache-busting typically uses hashes of the file contents; so that you're only cache-busting when the contents of the file have changed.

**Comment by chesio** [comment]
You're right, I should not use the term "decryption", it's not technically correct here.

> These hashes aren't being used for cryptography. They're being used for cache-busting public-facing client-side assets. There is no reason to treat it like it's sensitive data. That's bonkers.

May I then ask what is the actual use-case for the "Disable asset versioning" feature? As far as I'm concerned, version numbers do the job (cache busting) just fine for any core and plugin assets (as these files only change when WordPress/plugin version change) and for your own assets you can use whatever scheme works for you...

(I'm honestly curious, obviously I'm missing something here.)

**Comment by partounian** [comment]
Some CDNs supposedly don't cache URLs with query, but I haven't found that to be true for any I've worked with.

**Comment by chesio** [comment]
@partounian Thanks! I rarely deal with CDNs, so I didn't know that.

Apparently, Google Page Speed Insights recommended to remove query strings from static resources at one point ([source](https://ben.lobaugh.net/blog/201591/remove-query-strings-from-static-resources-in-wordpress)), but I fail to get this warning now and there is no explicit information on this under [HTTP Caching](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating-and-updating-cached-responses) chapter of their Web Fundamentals handbook.

I understand the benefits of having a fingerprint of the file, or a version number, embedded in asset's filename, but I was curious if there are any benefits of only dropping the version number from query string and doing nothing else.
