### ISSUE TITLE
Yoast sitemap taxonomy indexes are root relative

### ISSUE THREAD

**Issue by dcio** [roots/soil#194]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [X] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

Yoast SEO Sitemap taxonomy indexes (i.e. category-sitemap.xml & post_tag-sitemap.xml) are missing domain.

**What is the expected or desired behavior?**

Indexed taxonomy pages should contain full URL instead of root relative.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

On sites with both Soil & Yoast enabled the sitemaps for any taxonomy archives are root relative which are being flagged as invalid URLs.

Here's an example from your "Built with Sage" section on roots.io:

https://karmabaker.com/category-sitemap.xml
https://karmabaker.com/post_tag-sitemap.xml
https://karmabaker.com/product_cat-sitemap.xml
https://karmabaker.com/product_tag-sitemap.xml
https://karmabaker.com/ingredient-sitemap.xml

**Please describe your local environment:**

Soil version: 3.7.1

WordPress version: 4.8.1

Active theme: Custom

Active plugins: Yoast, Soil

**Where did the bug happen? Development or remote servers?**

Both

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://discourse.roots.io/t/soil-root-relative-url-plugins/10094/3

---

**Comment by dcio** [comment]
Adding the following to the [solution here](https://github.com/roots/soil/issues/156) fixed custom taxonomies:

```
remove_filter( 'get_taxonomies', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
remove_filter( 'get_taxonomy', 'Roots\\Soil\\Utils\\root_relative_url', 10 );
```

**Comment by mahnunchik** [comment]
Any news?
