### ISSUE TITLE
Gutenberg compatibility

### ISSUE THREAD

**Issue by yumyo** [roots/soil#203]
https://github.com/roots/soil/blob/1f16f9db5f9596bac24fdf57611d4da63362ee11/modules/clean-up.php#L93

The `clean_script_tag` function called by the `script_loader_tag` filter breaks Gutenberg. 
Otherwise Soil seems to work flawlessly.

**Comment by retlehs** [comment]
been using soil + gutenberg on a project recently and haven't run into any issues, closing since i'm assuming this is no longer relevant/gutenberg has gone through a ton of changes since
