### ISSUE TITLE
Soil's nice search doesn't work for special chars / umlauts

### ISSUE THREAD

**Issue by E-VANCE** [roots/soil#204]
- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

---

Using soil (3.7.3, in conjunction with Search WP) the search URL re-writes are throwing a 404 when cointaining umlauts (ü/ö/ä) – this only concerns some edge cases (German) but should be fixed doing forward probably...

**Comment by retlehs** [comment]
works for me, might be an issue with your webserver?

**Comment by E-VANCE** [comment]
Must be then, thanks for looking into this.
