### ISSUE TITLE
Root relative filtering of URLs returned to the post editor

### ISSUE THREAD

**Issue by Einkoro** [roots/soil#208]
Is there any reason 'post_link', 'post_type_link', and 'page_link' are not currently filtered for root relative URLs? Filtering them would return root relative URLs in the post editor when selecting a post, page or custom post type from the link dialog.

I'd be happy to open a pull request to add them if there is no objections.

**Comment by Einkoro** [comment]
Do you think it would be worth adding a ‘’add_theme_support’’ flag to enable root relative URLs in wp-admin for brave souls willing to risk potential problems?

**Comment by QWp6t** [comment]
You can now force enable it with a filter:

```php
add_filter('soil/load-module/relative-urls', '__return_true');
```
