### ISSUE TITLE
Soil's "Clean Up" brokes Gutenberg

### ISSUE THREAD

**Issue by ladislavsulc** [roots/soil#210]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**
Enabled settings `add_theme_support('soil-clean-up');` brokes the new Gutenberg editor. The screen of the error: https://i.imgur.com/xc04PD1.png

**What is the expected or desired behavior?**
For it to work.

---

## Bug report

Enabled settings `add_theme_support('soil-clean-up');` brokes the new Gutenberg editor - blank page. The screen of the error: https://i.imgur.com/xc04PD1.png. Commenting `add_theme_support('soil-clean-up');` makes it work again.

**Please describe your local environment:**
Soil version: Latest

```
add_theme_support('soil-clean-up');
add_theme_support('soil-disable-asset-versioning');
add_theme_support('soil-disable-trackbacks');
//add_theme_support('soil-google-analytics', 'UA-XXXXX-Y');
//add_theme_support('soil-jquery-cdn');
//add_theme_support('soil-js-to-footer');
add_theme_support('soil-nav-walker');
add_theme_support('soil-nice-search');
add_theme_support('soil-relative-urls');
```

WordPress version: Latest

Active theme: Yootheme Pro

Active plugins: No need to put it here, debugged them one by one, it is that one line in Soil.

**Where did the bug happen? Development or remote servers?**
Local and Production as well

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**
No

---

**Other relevant information:**
Thank you for looking into it.

**Comment by retlehs** [comment]
unable to reproduce on both local and production. have you tried with another theme?

**Comment by ladislavsulc** [comment]
@retlehs you are right. A different theme works. Guess I will write to their support or find another way around. Thank you.

**Comment by solidcolour** [comment]
I noticed the bug as well. After some research I found it is related to the script clean up part. If I remove that part, the new editor appears and works. Otherwise, browser shows up a blank screen when creating or editing a post/page, there are some script errors in console. Tested on Wordpress 5.0 and 5.0.1.

**Comment by retlehs** [comment]
if you are looking for support, please post on https://discourse.roots.io/ from a username associated with an email address that was used to purchase soil and we can help get you sorted!
