### ISSUE TITLE
Not all URLs relative

### ISSUE THREAD

**Issue by briggySmalls** [roots/soil#211]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

URLs of some of my menu items are not relative. Specifically those added by selecting:
- A page
- A post type archive

**What is the expected or desired behavior?**

The URLs for these items to be relative, as would be the case if the following were added to `$root_rel_filters`:
- `page_link`
- `post_type_archive_link`

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

- Enter site customiser
- Create a menu item from a post type archive
- Create a menu item from a page
- Publish and observe how URLs are not relative

**Please describe your local environment:**

Soil version: 3.7.3

WordPress version: 4.9.8

Active theme: Custom theme from Sage

Active plugins: TBC

**Where did the bug happen? Development or remote servers?**

Development machine

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by briggySmalls** [comment]
Note: related to https://github.com/roots/soil/issues/208#issuecomment-422437812

**Comment by QWp6t** [comment]
We might add this by default, but in the meantime you can accomplish this yourself by modifying the list of filters that relative URLs module adds.

This will work with any version of Soil since `3.5.0`.

```php
add_filter('soil/relative-url-filters', function ($filters) {
    return array_merge($filters, [
        'page_link',
        'post_link',
        'post_type_archive_link',
        'post_type_link',
    ]);
});
```
