### ISSUE TITLE
Nav walker filter interferes with other walkers

### ISSUE THREAD

**Issue by briggySmalls** [roots/soil#212]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

If soil's NavWalker is used on a page, menus that use other walkers have their CSS classes modified by the NavWalker.

This is because the filter added in the `Roots\Soil\Nav\NavWalker` constructor:
```php
add_filter('nav_menu_css_class', array($this, 'cssClasses'), 10, 2);
```
is never removed, and so a stale NavWalker object (out of scope) still handles the filter event for all subsequent menus.

**What is the expected or desired behavior?**

If a nav menu is created with an explicit custom nav walker, as below, it not to have it's CSS classes modified by Soil's nav walker.

```php
wp_nav_menu([
            'theme_location' => 'primary_navigation',
            'walker' => new MyNavWalker()]) 
```

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

1. Output two menu's, one using a custom walker
```php
{!! wp_nav_menu(['theme_location' => 'primary_navigation']) !!}
{!! wp_nav_menu([
    'theme_location' => 'primary_navigation',
    'walker' => new \Walker_Nav_Menu()]) !!}
```
2. Observe how the second nav menu's HTML does not have the default wordpress classes (e.g. `current-menu-item`)

**Please describe your local environment:**

Soil version: 3.7.3

WordPress version: 4.9.8

Active theme: Custom Sage-based theme

Active plugins: TBD

**Where did the bug happen? Development or remote servers?**

Development & remote server

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by briggySmalls** [comment]
I am happy to open a pull request to try and address this issue. I'm no pro, but perhaps the filter can be unregistered at the end of the walk function?

```php
public function walk( $elements, $max_depth )
{
    $output = call_user_func_array(['parent', 'walk'], func_get_args());
    // Unregister filters
    remove_filter('nav_menu_css_class', [$this, 'cssClasses']);
    remove_filter('nav_menu_item_id', '__return_null');

    // Return result
    return $output;
}
```

I've found this to work for my needs.

The downside of this is that the same nav walker cannot be used twice (filter only assigned in constructor, i.e. once in object's lifecycle). I would have thought this would be a rarer use case than wanting to use two walkers on the same page?

**Comment by lkraav** [comment]
Yes, it's an external (small) library, but I've been happy with https://github.com/stevegrunwell/one-time-callbacks

**Comment by briggySmalls** [comment]
Nice find. But the `nav_menu_css_class` filter is fired multiple times during the 'walk', depending on how many items the editor has added to the menu. So I'm not sure it would be possible to use that here.
