### ISSUE TITLE
'soil-clean-up' causes error in admin on WP 5.0

### ISSUE THREAD

**Issue by WraithKenny** [roots/soil#216]
#210 Was incorrectly closed.

If a theme has `add_theme_support('soil-clean-up');` in its `functions.php`, and this plugin is active, the javascript error **will** occur in the WP admin for WordPress 5.0 and higher.

The reason for that is clear: The regex at https://github.com/roots/soil/blob/master/modules/clean-up.php#L95 will affect https://core.trac.wordpress.org/browser/tags/5.0.2/src/wp-includes/script-loader.php#L191 which will cause `document.write( "<script src="...` (double-quote in a double-quote).

If, as in that ticket, "A different theme works." that is because that other theme isn't actually using `add_theme_support('soil-clean-up');` or isn't on WP 5.0 (`wp_get_script_polyfill` was added in 5.0.0).

**Comment by kevinlisota** [comment]
+1 We are experiencing the same issue when Soil is activated, and it is caused by the scriptloader tag cleanup. We are experiencing this on two sites that currently run Sage 8

**Comment by retlehs** [comment]
if you are looking for support, please post on https://discourse.roots.io/ from a username associated with an email address that was used to purchase soil and we can help get you sorted!
