### ISSUE TITLE
Relative attachment URLs even if filtered (The SEO Framework)

### ISSUE THREAD

**Issue by briggySmalls** [roots/soil#217]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

---

**What is the current behavior?**

Soil makes URLs obtained using `wp_get_attachment_url()` relative if 'The SEO framework' is installed, regardless of whether it is removed with `soil/relative-url-filters`.

This behaviour was implemented in #184.

**What is the expected or desired behavior?**

If `wp_get_attachment_url` is removed from the list of filters to apply Soil's relative URL modification to using `soil/relative-url-filters` then this should be honoured whether or not 'The SEO framework' is installed.

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

1. [Install The SEO Framework](https://wordpress.org/plugins/autodescription/)
2. Add the following filter to `soil/relative-url-filters`
```php
add_filter('soil/relative-url-filters', function ($filters) {
    return array_diff($filters, ['wp_get_attachment_url']);
});
```
3. Dump the output of a call to `wp_get_attachment_url` by adding the following action:
```php
add_action('the_seo_framework_do_after_output', function () {
  var_dump(wp_get_attachment_url(get_post_thumbnail_id()));
}, 11);
```
4. Navigate to a post that has a featured image.

**Please describe your local environment:**

Soil version: 3.7.3

WordPress version: 4.9.8

Active theme: Custom (sage-based)

Active plugins: The SEO Framework - 3.2.1

**Where did the bug happen? Development or remote servers?**

Both

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

None

**Comment by briggySmalls** [comment]
It should be noted that this only breaks things after `the_seo_framework_do_after_output`. In my case posts loaded using jetpacks infinite scroll.

**Comment by retlehs** [comment]
just tested a fresh vanilla 5.3 install with the seo framework and soil (with relative URLs enabled)

looks like something may have updated on TSF's end because i'm seeing non-relative URLs for social images
