### ISSUE TITLE
Soil is breaking Wordpress editor.

### ISSUE THREAD

**Issue by bsweaty** [roots/soil#220]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [README](https://github.com/roots/soil/blob/master/README.md) and followed its instructions (if applicable)

---

## Bug report
Take a look at current Soil usage(I've updated this a couple times as the issue is bigger than I thought. Initially this happened when I update plugins locally at the same time I was working on creating a Custom Post Type, however after more testing the CPT, or any code I have written, has no effect):

`add_theme_support('soil-clean-up');
    add_theme_support('soil-jquery-cdn');
    add_theme_support('soil-nav-walker');
    add_theme_support('soil-nice-search');
    add_theme_support('soil-relative-urls');`

The result is anytime you create a new post / page, or edit an existing, the admin throws a Javascript error and stays as a hidden white screen:
![image](https://user-images.githubusercontent.com/2700879/50914120-17df4680-13f3-11e9-83ba-2f4510b38524.png)
The DOM still exists in the admin, meaning it isn't a PHP error. When I disable the Soil plugin, the editor works just fine.
**Please describe your local environment:**

Soil version: 
![image](https://user-images.githubusercontent.com/2700879/50914310-86240900-13f3-11e9-957a-4dc040d7d207.png)

WordPress version: 5.0.2

Active theme: Sage

Active plugins: Lots, i turned all of them on and off, nothing else had an effect on the issue, hence why we are here.

**Where did the bug happen? Development or remote servers?**
Both local and production.

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**
[https://discourse.roots.io/t/blank-new-page-after-fresh-install/14544](https://discourse.roots.io/t/blank-new-page-after-fresh-install/14544)

**Comment by retlehs** [comment]
i'm unable to re-produce this issue with multiple themes and setups (vanilla and bedrock) with the latest WP and gutenberg.

if you are looking for support you'll need to have a license (i'm not seeing any record of you in our customer database based on your email address used on roots discourse)
