### ISSUE TITLE
style_loader_tag  filter breaks several admin pages

### ISSUE THREAD

**Issue by QuietNoise** [roots/soil#245]
## Description

**style_loader_tag** filter from CleanUp module breaks several admin pages _(mostly those created by themes/plugins)_.

## Steps to reproduce

1. Add `add_theme_support('soil-clean-up');` to functions.php
2. Have some third party plugins installed (issue confirmed on ACF, WP Migrate DB)
3. Go to some custom admin page _(i.e. /wp-admin/tools.php?page=wp-migrate-db if you have WP Migrate DB installed)_.
4. Observe broken styles.

Further steps to confirm the issue comes from this filter:
5. Comment out the filter activation in /wp-content/plugins/soil/modules/clean-up.php
`//add_filter('style_loader_tag', __NAMESPACE__ . '\\clean_style_tag');`
6. Observe the styles coming back to normal on the previously broken admin page.

**Expected behavior:** [What you expect to happen]
I would expect the module to not break the admin pages.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% on affected admin pages.

## Versions
WP: 5.3
Soil: 3.4.0

**Comment by retlehs** [comment]
fyi, this was addressed in an older update
