### ISSUE TITLE
not working: option should_load on Google Analytics feature

### ISSUE THREAD

**Issue by ligne13** [roots/soil#264]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The GA code is injected in the `<head>` even if the should_load option is set to false.

## Steps to reproduce

```
add_theme_support( 'soil', [
        'google-analytics' => [
            'should_load'         => false,
            'google_analytics_id' => 'UA-XXXX-XX',
            'optimize_id'         => null,
            'anonymize_ip',
        ],
    ] );
```

In the `<head>`:
```
<script>
      (function(s,o,i,l){s.ga=function(){s.ga.q.push(arguments);if(o['log'])o.log(i+l.call(arguments))}
    s.ga.q=[];s.ga.l=+new Date;}(window,console,'Google Analytics: ',[].slice))
    ga('create','UA-XXXX-XX','auto');
    ga('set','anonymizeIp',true);  ga('set','transport','beacon');ga('send','pageview');
</script>
```

**Expected behavior:** [What you expect to happen]

The `<script>` should not be present is the `should_load` option is `false`.

## Versions

Soil 4.0.4
Theme Sage 9.0.0
Wordpress 5.5.1
PHP 7.4

**Comment by chesio** [comment]
Hi @ligne13 ,

the script is still included for debugging purposes - if you inspect it closely you will notice that it does not send anything to Google Analytics instead it logs the `ga()` commands to browser's console.

**Comment by ligne13** [comment]
OK ! thank you.
