### ISSUE TITLE
Fatal error when install

### ISSUE THREAD

**Issue by marcelo2605** [roots/soil#53]
I'm trying to install solis but when I click to activate it, the following message appear:

Parse error: syntax error, unexpected T_STRING in /.../wp-content/plugins/soil-master/soil.php on line 14

I try the same in my local machine and I had no trouble with the installation.

**Comment by retlehs** [comment]
sounds like you're not running at least PHP 5.3

**Comment by marcelo2605** [comment]
Fixed! Thanks.

**Comment by matthisamoto** [comment]
I recently had this issue pop up only on live server, which says it's running PHP 5.6.27

```
PHP Parse error:  syntax error, unexpected T_STRING in /.../wp-content/plugins/soil/soil.php on line 14
```

PHP Version

```
PHP 5.6.27 (cli) (built: Oct 20 2016 20:14:23)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.2, Copyright (c) 2002-2016, by ionCube Ltd.
    with SourceGuardian v11.0.2, Copyright (c) 2000-2016, by SourceGuardian Ltd.
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by retlehs** [comment]
that says the cli version of php is 5.6. what about the version being served from your webserver? that error does not show up unless the server isn't running at least php 5.4

**Comment by matthisamoto** [comment]
The cPanel lists PHP at 	5.4.24

**Comment by retlehs** [comment]
cpanel says that but what about a `phpinfo`? anyway, you should take this up with support from your webhost as this is not an issue with the soil codebase

**Comment by matthisamoto** [comment]
Thanks for your response.
