### ISSUE TITLE
Allow module overrides and additions to be placed within themes.

### ISSUE THREAD

**Issue by QWp6t** [roots/soil#67]
Currently all modules are globbed and then compared against `add_theme_support(...)`.

I'm thinking we could glob a `modules/` directory within both the parent and child theme directories.

This could work in tandem with Sage as well. Right now we're discussing removing the gallery from Sage to make it less dependent on Bootstrap. This is where a user-defined module could come in handy, as a developer could re-add a module for a Bootstrap gallery, then toss in `add_theme_support('soil-gallery')` and it would automatically look for, for example, `modules/soil-gallery.php` in their theme folder. I believe we're also discussing similar framework-agnostic changes with NavWalker; again, it could be moved to Soil and then an override could be placed by the user in their theme. Or users can simply invent their own modules that don't exist in Soil at all.

This would allow developers to make use of the options class as well, and we could probably expand Soil a bit to make it cater more to this sort of thing.

**Comment by retlehs** [comment]
another use case: #96

**Comment by QWp6t** [comment]
Closing this for now. It's been more than a year. We can revisit this idea at a later date.

Once Sage 9 is done, I'll likely focus my attention on Soil, and I'll add this to it.
