### ISSUE TITLE
Invalid Jquery CDN

### ISSUE THREAD

**Issue by christianmagill** [roots/soil#74]
I'm getting an invalid jQuery CDN url as the version number is not being retrieved properly.

Final output is...
```
<script src="//ajax.googleapis.com/ajax/libs/jquery//jquery.min.js"></script>
```

**Comment by retlehs** [comment]
does this fix it? https://github.com/roots/soil/commit/65b73dc5cba4a0f266ddd1e9aafff9d9019366c5

**Comment by christianmagill** [comment]
Yes, thanks
