### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by khromov** [roots/soil#92]
I see that Soil is available for sale at:
https://roots.io/plugins/soil/

I know some other plugins employ a similar model (ie. they are available on GitHub gratis, but you are really paying for support), but they rarely have a "per-site" payment model.

I guess what I am wondering about is:
What do you get when you purchase Soil through Roots.io?

**Comment by retlehs** [comment]
we are encouraging purchases for the commercial use of soil. you will receive support when you purchase it as well.

i don't think the per-site payment model is rare at all - but there's also nothing in the code (as you can see in this repo) that is doing any sort of license checking, fwiw (honor system)

please use [our discourse](https://discourse.roots.io/) in the future for questions. thanks!
