### ISSUE TITLE
Google Analytics Demographics requires hack

### ISSUE THREAD

**Issue by evanfuture** [roots/soil#96]
In order to use GA's Demographics features (recording age/gender when possible), you need to add this line to the ga codeblock:
ga('require', 'displayfeatures');

As of now, that means hacking it into the module directly and revising when the plugin is updated.  I'd add a new option, but I'm not sure if you guys want to do that.  The other option is to not use soil for this at all...

**Comment by QWp6t** [comment]
You can add this to your page any time after the snippet

```
<script>ga.q.splice(1, 0, ['require','displayfeatures']);</script>
```

**Comment by evanfuture** [comment]
That's a good fix for now, but I would like to see a way to integrate it into the plugin.

**Comment by retlehs** [comment]
>  The other option is to not use soil for this at all...

this is the best option. we'll be keeping the snippet as simple as possible in soil for now.
